services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      # PostgreSQL - Aiven
      SPRING_DATASOURCE_URL: jdbc:postgresql://it3930-manh-80a8.l.aivencloud.com:12419/defaultdb?sslmode=require
      SPRING_DATASOURCE_USERNAME: avnadmin
      SPRING_DATASOURCE_PASSWORD: AVNS_s2Y7cL60H99pMRjY2sR
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

      # JPA / Hibernate
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"

      # Mail
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: "587"
      SPRING_MAIL_USERNAME: ducm5365@gmail.com
      SPRING_MAIL_PASSWORD: vgansybnrzowwltm
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"

      # Tomcat Session
      SERVER_SERVLET_SESSION_PERSISTENT: "false"
